### ISSUE TITLE
Error during load user from file (after second start)

### ISSUE THREAD

**Issue by KatNezabydka** [KatNezabydka/project-educate1#22]
!!! Loading users from the file: users_data.json !!!
Traceback (most recent call last):
  File "/Users/kornyshevaekaterina/Documents/GoIt/Projects/project-educate1/src/Birthday.py", line 10, in wrapper
    datetime.strptime(value, "%d.%m.%Y")
TypeError: strptime() argument 1 must be str, not None

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/kornyshevaekaterina/Documents/GoIt/Projects/project-educate1/src/__main__.py", line 221, in <module>
    main()
  File "/Users/kornyshevaekaterina/Documents/GoIt/Projects/project-educate1/src/__main__.py", line 181, in main
    fake_user.add_birthday(user["birthday"])
  File "/Users/kornyshevaekaterina/Documents/GoIt/Projects/project-educate1/src/Record.py", line 43, in add_birthday
    self.birthday = Birthday(birthday)
  File "/Users/kornyshevaekaterina/Documents/GoIt/Projects/project-educate1/src/Birthday.py", line 12, in wrapper
    raise ValidationError("Incorrect date format. Use DD.MM.YYYY.")
ValidationError.ValidationError: Incorrect date format. Use DD.MM.YYYY.

**Comment by KatNezabydka** [comment]
https://github.com/KatNezabydka/project-educate1/pull/34
